### ISSUE TITLE
Evento da comunidade presencial

### ISSUE THREAD

**Issue by fredsonchaves07** [soujava/comunidade#4]
Olá galera do SouJava!! Como vocês estão?? 

Não sei se aqui é o espaço para minha dúvida... mas vamos lá :) 

O que acha da ideia de ter um evento presencial do SouJava? Já houve diminuição dos casos COVID em algumas cidades e os eventos presenciais estão retornando aos poucos. Eu vejo que a comunidade Python é bem ativa em relação aos eventos. 
https://2022.pythonbrasil.org.br/
Acredito que seria massa ter algo do tipo voltado para o ecossistema Java.

**Comment by dearrudam** [comment]
Valeu pela pergunta @fredsonchaves07 ! 

E sim, acredito que iremos ter eventos presenciais, só não temos ainda data.

Mas assim que tivermos novidades, a gente vai atualizando aqui nesse repositório e em nossas [redes sociais](https://github.com/soujava/comunidade#nossas-redes-sociais), okay!?
